[2025-09-16T14:12:05.166+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-16T14:12:05.201+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nakhonpathom_waste_csv_etl_dag.transform_data manual__2025-09-16T14:11:56.517190+00:00 [queued]>
[2025-09-16T14:12:05.215+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nakhonpathom_waste_csv_etl_dag.transform_data manual__2025-09-16T14:11:56.517190+00:00 [queued]>
[2025-09-16T14:12:05.216+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-16T14:12:05.238+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-09-16 14:11:56.517190+00:00
[2025-09-16T14:12:05.248+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=175) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-16T14:12:05.251+0000] {standard_task_runner.py:63} INFO - Started process 177 to run task
[2025-09-16T14:12:05.251+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nakhonpathom_waste_csv_etl_dag', 'transform_data', 'manual__2025-09-16T14:11:56.517190+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/hazardous_waste_etl_dag.py', '--cfg-path', '/tmp/tmp90pebzpk']
[2025-09-16T14:12:05.253+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask transform_data
[2025-09-16T14:12:05.323+0000] {task_command.py:426} INFO - Running <TaskInstance: nakhonpathom_waste_csv_etl_dag.transform_data manual__2025-09-16T14:11:56.517190+00:00 [running]> on host 29fe93b12185
[2025-09-16T14:12:05.434+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nakhonpathom_waste_csv_etl_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T14:11:56.517190+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-16T14:11:56.517190+00:00'
[2025-09-16T14:12:05.437+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-16T14:12:05.438+0000] {logging_mixin.py:188} INFO - Starting data transformation...
[2025-09-16T14:12:05.472+0000] {logging_mixin.py:188} INFO - Data transformed successfully. Final columns: ['fiscal_year', 'district', 'local_admin_org', 'waste_amount', 'unit']
[2025-09-16T14:12:05.501+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-16T14:12:05.502+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-16T14:12:05.513+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nakhonpathom_waste_csv_etl_dag, task_id=transform_data, run_id=manual__2025-09-16T14:11:56.517190+00:00, execution_date=20250916T141156, start_date=20250916T141205, end_date=20250916T141205
[2025-09-16T14:12:05.548+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-16T14:12:05.573+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-16T14:12:05.577+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
