[2025-09-16T15:12:15.689+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-16T15:12:15.710+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nakhonpathom_waste_csv_etl_dag.transform_data manual__2025-09-16T15:12:07.874328+00:00 [queued]>
[2025-09-16T15:12:15.719+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nakhonpathom_waste_csv_etl_dag.transform_data manual__2025-09-16T15:12:07.874328+00:00 [queued]>
[2025-09-16T15:12:15.722+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-16T15:12:15.736+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-09-16 15:12:07.874328+00:00
[2025-09-16T15:12:15.745+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=205) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-16T15:12:15.747+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nakhonpathom_waste_csv_etl_dag', 'transform_data', 'manual__2025-09-16T15:12:07.874328+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/hazardous_waste_etl_dag.py', '--cfg-path', '/tmp/tmp58ltrjwv']
[2025-09-16T15:12:15.748+0000] {standard_task_runner.py:63} INFO - Started process 207 to run task
[2025-09-16T15:12:15.749+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask transform_data
[2025-09-16T15:12:15.797+0000] {task_command.py:426} INFO - Running <TaskInstance: nakhonpathom_waste_csv_etl_dag.transform_data manual__2025-09-16T15:12:07.874328+00:00 [running]> on host aa7dbbbc41c4
[2025-09-16T15:12:15.881+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nakhonpathom_waste_csv_etl_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T15:12:07.874328+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-16T15:12:07.874328+00:00'
[2025-09-16T15:12:15.883+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-16T15:12:15.885+0000] {logging_mixin.py:188} INFO - Starting data transformation...
[2025-09-16T15:12:15.913+0000] {logging_mixin.py:188} INFO - Data transformed successfully. Final columns: ['fiscal_year', 'district', 'local_admin_org', 'waste_amount', 'unit']
[2025-09-16T15:12:15.948+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-16T15:12:15.949+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-16T15:12:15.959+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nakhonpathom_waste_csv_etl_dag, task_id=transform_data, run_id=manual__2025-09-16T15:12:07.874328+00:00, execution_date=20250916T151207, start_date=20250916T151215, end_date=20250916T151215
[2025-09-16T15:12:16.004+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-16T15:12:16.025+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-16T15:12:16.029+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
